### ISSUE TITLE
Getting `robe-complete--variables: Search failed`

### ISSUE THREAD

**Issue by raghavio** [dgutov/robe#149] opened 2024-12-23 09:28 UTC
I can't seem to figure out why this keeps happening occasionally. Say I have code that looks something like this:
```
def extract_identifier(x)
  ...
end

def func_1(x)
  identifier = extract_identifier(x)
  ...
end

def func_2!(x)
  identifier = extract_identifier(x)
  ...
end
```

When I try to jump to the `extract_identifier` method from the `func_1` it works as expected. However, when I do the same from `func_2` it throws the below error:

```
robe-complete--variables: Search failed: "^[	 ]*def[	 ]*\\(?:[:A-Za-z]+\\.\\)?func_2!\\_>"
```

I've tried a bunch of things including hitting robe-refresh but nothing worked.

I'm on Emacs 29.4 and latest Robe version.

**Comment by dgutov** [comment] 2024-12-24 23:49
Hi!

"latest Robe" is the version from MELPA, right?

Do you use the built-in ruby-mode from Emacs (recommended), or some alternative like `enh-ruby-mode`?

Any chance you can narrow down to a specific code example which shows this error?

Usually this kind of error could come up depending on how the destination class is written, so it would either be always triggered, or not. In any case, I haven't managed to repro with your example above, and that would help with fixing.

**Comment by dgutov** [comment] 2024-12-24 23:53
Also, when it starts to happen again you can `M-x toggle-debug-on-error`, which should pop up the backtrace buffer the next time the error is triggered. You can copy the backtrace here in a comment.

**Comment by raghavio** [comment] 2024-12-25 09:28
Hello! Thanks for the quick response. I can't reproduce it right now, but I'll enable the debug toggle next time it happens. The code example I've shared is pretty much specific with just some stuff removed and things renamed. All the methods belong to the same class.

Yep, latest Robe from MELPA. I'm on version 20240509.155. I'm using the `ruby-ts-mode`.

**Comment by raghavio** [comment] 2024-12-25 17:34
Okay, I am able to reproduce it. I didn't realize that I had my lsp server turned on earlier. Which is why it worked.

Anyway, here you go. This is the exact code I tested this on:
```ruby
class Test
  def extract_identifier(_x)
    a = 1
  end

  def func_1(x)
    identifier = extract_identifier(x)
  end

  def func_2!(x)
    identifier = extract_identifier(x)
  end
end
```

This is from the Messages buffer:
```
Debug on Error enabled globally
Entering debugger...
eldoc error: (search-failed ^[	 ]*def[	 ]*\(?:[:A-Za-z]+\.\)?func_1\_>)
eldoc error: (search-failed ^[	 ]*def[	 ]*\(?:[:A-Za-z]+\.\)?func_2!\_>)
robe-complete--variables: Search failed: "^[	 ]*def[	 ]*\\(?:[:A-Za-z]+\\.\\)?func_2!\\_>"
eldoc error: (search-failed ^[	 ]*def[	 ]*\(?:[:A-Za-z]+\.\)?extract_identifier\_>)
eldoc error: (search-failed ^[	 ]*def[	 ]*\(?:[:A-Za-z]+\.\)?func_2!\_>)
robe-complete--variables: Search failed: "^[	 ]*def[	 ]*\\(?:[:A-Za-z]+\\.\\)?func_2!\\_>"
```

This is from the Backtrace buffer. Surprisingly, this showed up when the jump worked from `func_1`.
```
Debugger entered--Lisp error: (search-failed "^[\11 ]*def[\11 ]*\\(?:[:A-Za-z]+\\.\\)?extract_identifie...")
  robe-complete--local-variables("extract_identifier")
  robe-complete--variables(t "extract_identifier")
  robe-call-context()
  robe-eldoc()
  apply(robe-eldoc nil)
  #f(advice robe-eldoc :after-until #f(compiled-function (&rest args) #<bytecode 0x18031ef701b24f4a>))()
  eldoc--invoke-strategy(nil)
  eldoc-print-current-symbol-info()
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_12>()
  apply(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_12> nil)
  timer-event-handler([t 0 0 500000 nil #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_12> nil idle 0 nil])
```

**Comment by dgutov** [comment] 2024-12-26 04:53
Great! Thanks, this was indeed `ruby-ts-mode` (I really should switch to it full-time myself), with a missing piece in Emacs' syntax integration.

Just [pushed a fix](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b561f896b5e52d3e4571901fd5d545354ba29bac) into Emacs master, and a workaround here for the stable users.

**Comment by dgutov** [comment] 2024-12-26 04:53
Try it out, please lmk if the problem is still there.

**Closed by dgutov** 2024-12-26 04:53 UTC

**Comment by raghavio** [comment] 2024-12-26 09:35
It is working now. Awesome! Appreciate the super quick fix. Thank you!!
