### ISSUE TITLE
Company robe hangs before presenting completions

### ISSUE THREAD

**Issue by dgtized** [dgutov/robe#36] opened 2014-07-26 22:31 UTC
I've been encountering a problem where completion frequently hangs. I enter 3 characters pause for a second, completion kicks in, and just hangs with the message "Contacting host: 127.0.0.1:24969". I've waited at least 30s and had no response. After using `C-g` to abort, it immediately presents a list of completions. 

I benchmarked the robe server by adding request time information to the requests, and all completion lists were handled in < 0.25s, so it's not hanging on the server. I also benchmarked calling `robe-request` and that responded quickly, so it does not appear to be anything on the parsing edge of emacs.

```elisp
(benchmark-run 10
  (robe-request "complete_method" "after" nil "ApplicationController" nil))

;; => (0.22050937399999998 0 0.0)
```

I then tried edebug on `company-abort` and found that `C-g` was not triggering that. So I used `(setq debug-on-quit t)` to diagnose what was blocking. Sometimes this resulted in the completion working without blocking, but when it did, the abort backtrace was:

```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

So as soon as that is aborted it jumps back into company and displays the options.

I tried mucking around with `company-echo-delay`, and have a hunch this is related to eldoc making timer requests at the same time as robe. I haven't had much luck disabling eldoc. It's also tricky to test because occasionally completion just works, so it's tricky to tell if fiddling with something improved it, or I just randomly got a couple of completions to work.

I'm happy to try and work on a test case, but wanted to document what I have thus far, and see if anyone else had ideas.

**Comment by Nollo** [comment] 2015-02-12 04:03
Hello,
I have the same problem. I installed robe, enh-ruby, company, projectile rails. So when I open a old or new rails project, I do "robe-start", I have the "Contacting host: 127.0.0.1:24969" message. But no window appears (but *rails buffer is created, and I can use pry)
When I open a rb file, I just write "put", and I get "Contacting host: 127.0.0.1:24969". Emacs is stuck until I do "Ctrl + G" to unstuck Emacs, and nothing happenned.

In my Gemfile I have these two lines:
gem 'pry-rails'
gem 'pry-doc'

**Comment by dgutov** [comment] 2015-02-12 09:32
@Nollo What does your *rails* buffer say?

Do you maybe have a proxy configured?

**Comment by dgutov** [comment] 2015-02-12 09:33
@chalmagean Was installing company-mode the only change? Does the problem go away if you uninstall it, restart Emacs, then launch Robe and try to use it?

**Comment by Nollo** [comment] 2015-02-12 17:08
No proxy, it's my personnal computer.

More detailed actions:
I open emacs
I open my rails project
I do "robe-mode"
I do "robe-start"
No ruby console running. Launch automatically?(yes or no), I put yes and Enter
Rails environment: development
Contacting host: 127.0.0.1:24969 is displayed until I click somewhere in emacs (or do any action)
A rails buffer is created:
```
Loading development environment (Rails 4.2.0)
[0G[1] pry(main)> => "robe on"
[2] pry(main)> 
```
On a .rb file, I just type "put" and emacs just got stuck, with Contacting host: 127.0.0.1:24969 displayed

I can unstuck emacs with C+g, but nothing happened

**Comment by dgutov** [comment] 2015-02-12 17:39
@Nollo What's your OS? What completion framework are you using? Does Emacs freeze if you try to use any other Robe function, like `robe-doc` (`C-c C-d`)?

Would you like to post a sample project, with Gemfile and Gemfile.lock checked in, where you can observe the problem?

**Comment by Nollo** [comment] 2015-02-12 19:13
OS X 10.10.1
I have ruby (2.2.0) on rails (4.2.0) with rbenv (0.4.0).

I tried with the same file, so I have written "puts", I do the command and I get this:
Contacting host: 127.0.0.1:24969 (very quick, before displaying the next line)
Module:
( i press enter)
I have this in a buffer
````
Kernel#puts(args...)

Visibility: private

Equivalent to

    $stdout.puts(obj, ...)

Source

static VALUE
rb_f_puts(int argc, VALUE *argv, VALUE recv)
{
    if (recv == rb_stdout) {
	return rb_io_puts(argc, argv, recv);
    }
    return rb_funcall2(rb_stdout, rb_intern("puts"), argc, argv);
}
```
And here is the message buffer
```
Contacting host: 127.0.0.1:24969 [2 times]
Error in post-command-hook (ido-exhibit): (wrong-type-argument characterp "Kernel#")
Contacting host: 127.0.0.1:24969
Type C-x 1 to delete the help window.
Making delay-mode-hooks buffer-local while locally let-bound!
user-error: Minibuffer window is not active
Mark set
funcall-interactively: End of buffer
next-line: End of buffer
mwheel-scroll: Beginning of buffer [7 times]
Mark set
```

I clonned the rails project: https://github.com/Nollo/rails-test-robe-company

PS: Should company be launched AFTER robe ? or order doesn't matter ?

**Comment by dgutov** [comment] 2015-02-13 02:45
> I have this in a buffer

So the basic functionality works. That's good.

> Error in post-command-hook (ido-exhibit): (wrong-type-argument characterp "Kernel#")

I wonder when this happens. Probably unrelated to the current problem, but if you have steps to reproduce, please let me know.

> I clonned the rails project: https://github.com/Nollo/rails-test-robe-company

This one's empty.

> PS: Should company be launched AFTER robe ? or order doesn't matter ?

Makes no difference.

If all else fails, you should try using `company-robe` like documented in the README. According to earlier comments here, it might fix this.

The default completion (using CAPF) is a bit more flexible (but slower, when that flexibility comes into play). I don't have any freezes with it myself, though, so it would be good to get to the root of the problem.

**Comment by Nollo** [comment] 2015-02-13 03:37
* Sorry, I updated the repo, now you have it.

* I tried this:
I type put, before typing "s" emacs is stuck with the connecting message
I do ```C+g``` to kill it
My cursor is like this ```put|```
I do ```company-robe````
the popup is displayed with put* method !

* Error in post-command-hook (ido-exhibit): (wrong-type-argument characterp "Kernel#")
Whe my cursor is like this ```put|```
I do ``` robe-doc ```
Before I get ``` Module: ``` I have the error message displayed ``` Error in post-command-hook (ido-exhibit): (wrong-type-argument characterp "Kernel#") ```

**Comment by dgutov** [comment] 2015-02-13 12:55
@Nollo Thanks.

> (ido-exhibit): (wrong-type-argument characterp "Kernel#")

I still haven't managed to reproduce this one. Do you maybe have some Ido-related customizations, like having `ido-hacks` installed?

> I type put, before typing "s" emacs is stuck with the connecting message

It seems I've managed to reproduce this one, only with a different method, and only triggered sometimes. Looking into it.

**Comment by Nollo** [comment] 2015-02-13 19:02
I have this in my init.el
* For company (in custom variable)
```
 '(company-scrollbar-bg ((t (:background "#323445"))))
 '(company-scrollbar-fg ((t (:background "#393939"))))
 '(company-tooltip ((t (:inherit default :background "#21222d"))))
 '(company-tooltip-common ((t (:inherit font-lock-constant-face))))
 '(company-tooltip-selection ((t (:inherit font-lock-function-name-face))))
```
* For ido related things
```
(smex-initialize)
(global-set-key (kbd "M-x") 'smex)
(ido-mode 1)
(ido-vertical-mode 1)
(ido-everywhere 1)
(flx-ido-mode 1)
;; disable ido faces to see flx highlights.
(setq ido-enable-flex-matching t)
(setq ido-use-faces nil)
```
I also have ido-vertical-mode installed

**Comment by dgutov** [comment] 2015-02-13 19:10
> For ido related things...

Have you tried disabling `flx-ido-mode` or `ido-vertical-mode`, to see if that would fix the error?

**Comment by Nollo** [comment] 2015-02-15 09:58
Hey !
Well, I commented ``` (ido-vertical-mode 1) ``` and it works. So there is an issue with this package. Do you want me to create another issue to track it ?

**Comment by dgutov** [comment] 2015-02-15 14:44
That's a good find, but I can't reproduce it with `ido-vertical-mode` myself. Anyway, that seems to be a bug in that mode, so (after trying the latest version), you should report it to [that tracker](https://github.com/gempesaw/ido-vertical-mode.el/issues).

**Comment by dgutov** [comment] 2015-02-15 17:26
@Nollo What's your Emacs version?

Does anybody see the freezing problem with the Emacs 24.4 release, or an earlier version?

**Comment by dgtized** [comment] 2015-02-15 17:47
@dgutov I originally reported this issue on 24.4 pre-release.

**Comment by dgutov** [comment] 2015-02-15 17:56
@dgtized The `24.4.50.1` version that you reported was from Emacs trunk, I think. The 24.4 pre-release, at the time, would have been something like `24.3.51.1`.

**Comment by dgutov** [comment] 2015-02-16 01:16
I've filed http://debbugs.gnu.org/19860.

For now, it seems the best solution is to disable ElDoc support: `(setq robe-turn-on-eldoc nil)`.

**Comment by Nollo** [comment] 2015-02-16 07:21
I have ```GNU Emacs 25.0.50.1```installed with homebrew

**Comment by Nollo** [comment] 2015-04-19 18:41
Any news about the bug ?

**Comment by dgutov** [comment] 2015-04-24 12:22
@Nollo Not much so far, as you can see at the page linked above.

**Comment by dgutov** [comment] 2015-04-26 04:45
Good news everyone!

This should work fine in Emacs master starting with `2c1b860`. Please try it out.

**Comment by epchris** [comment] 2015-04-26 13:56
@dgutov What was the issue?

**Comment by epchris** [comment] 2015-04-26 13:58
for the curious: https://github.com/emacs-mirror/emacs/commit/2c1b8604946efbcd8ec5dd6c6dda7541ce4fc3c0

**Comment by dgutov** [comment] 2015-04-26 18:15
@epchris Did that also fix your "hangs my entire system" problem?

**Comment by epchris** [comment] 2015-04-26 19:25
I'll have a chance to update and try it out on monday and will try to let
you know how it goes.

**Comment by Nollo** [comment] 2015-04-27 18:39
hi folks, I updated my emacs today and I tested the same scenario. Nice work ! Emacs is not frozen anymore when completion is called.

**Comment by dgutov** [comment] 2015-04-27 21:05
Great, thanks for checking. I'm closing this now, until someone sees the problem again.

**Closed by dgutov** 2015-04-27 21:05 UTC

**Comment by jhirn** [comment] 2015-04-28 16:04
Dmitry, you are the man! Thanks for your persistence on getting this resolved. 

Will this be merged into the next release of emacs? I'd like to avoid using the master branch.

**Comment by dgutov** [comment] 2015-04-28 18:55
The regression was introduced in master, and fixed there.

The next release will probably branch from master too, but if not, it shouldn't contain the regression in the first place.

**Comment by dgutov** [comment] 2015-04-28 18:56
So if you can actually reproduce it in 24.3, as you stated above, we'll need more details. Step-by-step scenario would be best.

**Comment by jhirn** [comment] 2015-04-28 19:12
I'm on 24.5.1 but I disabled capf completion a while ago so I don't have
this problem anymore, but I never had the master version installed so I'm
not sure if my issue was identical or simply related.

If I can reproduce it I'll give you the steps...

**Comment by dgutov** [comment] 2015-04-29 00:05
@jhirn

It's very unlikely to be identical. Thanks in advance.

**Comment by bdevel** [comment] 2021-01-14 20:07
Anyone else having issues with emacs freezing on Rakefiles, I found disabling `ruby-smie` solves my issue. ruby-smie is enabled automatically by `ruby-mode` for indenting. Disable it with `(setq ruby-use-smie nil)`

**Comment by dgutov** [comment] 2021-01-14 20:19
@bdevel Never seen this. Please `M-x report-emacs-bug` with some example code.
